### ISSUE TITLE
USER STORY: login account

### ISSUE THREAD

**Issue by b1ndark** [b1ndark/project4#1]
As a **User** I can **login** so that **I can load my account**

##  Acceptance Criteria:

- **Acceptance Criteria 1**
**Given** that I can access Sign in link in navbar
**Then** I can click

- **Acceptance Criteria 2**
**Given** that the login page is setup up
**Then** I can type my username and password

- **Acceptance Criteria 3**
**Given** that I have an account
**Then** I can access my account profile

## Tasks

- [x] **Task 1 -** Setup a login page
- [x] **Task 2 -** Input boxes for username and password
- [x] **Task 3 -** Check for username in database, if something wrong message is displayed
- [x] **Task 4 -** Checks for matching passwords, if something wrong message is displayed
- [x] **Task 5 -** Checks for matching username and password, if something wrong message is displayed
- [x] **Task 6 -** connect login navbar link to login page
