### ISSUE TITLE
USER STORY: Post images

### ISSUE THREAD

**Issue by b1ndark** [b1ndark/project4#10]
As a **User** I can **post images** so that **it helps identifying the post**

## Acceptance Criteria

- **Acceptance Criteria 1**
**Given** that I want decorate the Post
**Then** I can add pictures to it

- **Acceptance Criteria 2**
**Given** that User didn't add any photos
**Then** a default picture is displayed

## Tasks

- [x] **Task 1 -** Setup a add picture feature
- [x] **Task 2 -** Display the added photo
- [x] **Task 3 -** Display a default photo if User didn't add any
