### ISSUE TITLE
USER STORY: Pagination Posts

### ISSUE THREAD

**Issue by b1ndark** [b1ndark/project4#15]
As a **User** I can **select next page** so that **I don't need to scroll**

## Acceptance Criteria

- **Acceptance Criteria 1**
**Given** that there are more than four posts 
**Then** a pagination system is in place

- **Acceptance Criteria 2**
**Given** that I have clicked NEXT page
**Then** I am taken to the next page where I can visualize the posts and go back

## Tasks

- [x] **Task 1 -** Setup a pagination system to forum page
- [x] **Task 2 -** Max of four posts per page
- [x] **Task 3 -** Next and Previous page buttons
