### ISSUE TITLE
USER STORY: Navigation menus

### ISSUE THREAD

**Issue by b1ndark** [b1ndark/project4#16]
As a **User** I can **see navigation menus** so that **I can select the required page**

##  Acceptance Criteria:

- **Acceptance Criteria 1**
**Given** that I can access the menus
**When** I look at the navbar

- **Acceptance Criteria 2**
**Given** that I can select the page I want
**When** I click on the navbar link

## Tasks

- [x] **Task 1 -** Build/setup a navbar
- [x] **Task 2 -** Add the pages links to the navbar
- [x] **Task 3 -** Connect the links to their respective pages
