### ISSUE TITLE
USER STORY: Profile Page

### ISSUE THREAD

**Issue by b1ndark** [b1ndark/project4#18]
As a **User** I can **view Profile page** so that **I can modify or view other users profile**

## Acceptance Criteria

- **Acceptance Criteria 1**
**Given** that I want to see other Users profile
**Then** I can access it by clicking on the username

- **Acceptance Criteria 2**
**Given** that I have clicked it 
**Then** I am taken to the profile page

## Tasks

- [x] **Task 1 -** Setup a profile page
- [x] **Task 2 -** Add profile links to usernames
- [x] **Task 3 -** Link the username link to the Profile page
- [x] **Task 4 -** Once clicked on Username, User is taken to profile page
