### ISSUE TITLE
USER STORY: Posts/Forum Page

### ISSUE THREAD

**Issue by b1ndark** [b1ndark/project4#19]
As a **User** I can **select Forum page** so that **I can view posts**

## Acceptance Criteria

- **Acceptance Criteria 1**
**Given** that I have the forum link in the navbar
**When** I click on in it
**Then** the Forum page opens

- **Acceptance Criteria 2**
**Given** that the Forum page opened 
**Then** I can see the Posts done by Users

## Tasks

- [x] **Task 1 -** Create a Forum page
- [x] **Task 2 -** Add a Forum page to the navbar 
- [x] **Task 3 -** Link it to the Forum page
- [x] **Task 4 -** Post list view
