### ISSUE TITLE
USER STORY: Sign up

### ISSUE THREAD

**Issue by b1ndark** [b1ndark/project4#2]
As a **User** I can **sign up/register** so that **I can login**

##  Acceptance Criteria:

- **Acceptance Criteria 1**
**Given** that I can access the signup in navbar
**Then** I click in signup link

- **Acceptance Criteria 2**
**Given** that I clicked in it
**Then** I am taken to a signup page

- **Acceptance Criteria 3**
**Given** that I filed the required input boxes
**Then** I press Signup

- **Acceptance Criteria 4**
**Given** that I have Signed up
**Then** I get a confirmation message

## Tasks

- [x] **Task 1 -** Setup a Signup page
- [x] **Task 2 -** Add Signup link to navbar
- [x] **Task 3 -** Connect the navbar link to the page
- [x] **Task 4 -** Setup a Signup form
- [x] **Task 5 -** After clicking Signup User gets redirected to home page
- [x] **Task 6 -** Display a confirmation message
