### ISSUE TITLE
USER STORY: Contact Page

### ISSUE THREAD

**Issue by b1ndark** [b1ndark/project4#20]
As a **User** I can **access Contact page** so that **I can make inquiries or contact support**

## Acceptance Criteria

- **Acceptance Criteria 1**
**Given** that I want to contact the support of the forum
**Then** I can access it by clicking on contact link in the navbar

- **Acceptance Criteria 2**
**Given** that I have clicked it 
**Then** I am taken to the contact page

- **Acceptance Criteria 3**
**Given** that I been taken to the contact page
**Then** I get presented with a form that I fill and submit

- **Acceptance Criteria 4**
**Given** that I have submitted the form
**Then** I am redirected to Home page and a confirmation message is displayed

## Tasks

- [x] **Task 1 -** Setup a contact page
- [x] **Task 2 -** Add Contact link to the navbar
- [x] **Task 3 -** Link the contact link to the page
- [x] **Task 4 -** Once form is submitted Redirect to Home page
- [x] **Task 5 -** A confirmation message is displayed
