### ISSUE TITLE
USER STORY: Easy to Navigate

### ISSUE THREAD

**Issue by b1ndark** [b1ndark/project4#21]
As a **User** I can **access easily to menus** so that **I can navigate easily through the website**

##  Acceptance Criteria:

- **Acceptance Criteria 1**
**Given** that I can access the menus
**When** I look at the navbar

- **Acceptance Criteria 2**
**Given** that I can select the page I want
**When** I click on the navbar link

- **Acceptance Criteria 3**
**Given** that I can click back button
**When** I access the posts
**Then** I got back to posts view

- **Acceptance Criteria 4**
**Given** that a page is opened
**When** I clicked on the navbar links
**Then** a active link decoration is implemented to the respective page

## Tasks

- [x] **Task 1 -** Build/setup a navbar
- [x] **Task 2 -** Add the pages links to the navbar
- [x] **Task 3 -** Connect the links to their respective pages
- [x] **Task 4 -** Add Back button to the posts so user can go back to Forum page/view Posts
- [x] **task 5 -** Add a decoration to the active link so User knows which page is on
