### ISSUE TITLE
USER STORY: Admin

### ISSUE THREAD

**Issue by b1ndark** [b1ndark/project4#22]
As a **Admin** I can **login** so that **I can manage the forum**

##  Acceptance Criteria:

- **Acceptance Criteria 1**
**Given** that I am an Admin I access the Admin page
**When** I opened the Admin Tab
**Then** I can Delete/Modify

- **Acceptance Criteria 2**
**Given** that I can manage the Users
**When** in the Users Section within the Admin Page
**Then** I can Delete/Modify

- **Acceptance Criteria 3**
**Given** that I can manage Users Profiles
**When** in Users Profiles Section within the Admin Page
**Then** I can Delete/Modify

- **Acceptance Criteria 4**
**Given** that I can manage comments done by Users
**When** in Comments Section within the Admin Page
**Then** I can Delete/Modify

## Tasks

- [x] **Task 1 -** Setup Admin account
- [x] **Task 2 -** Add Admin permissions to update/delete Users
- [x] **Task 3 -** Add Admin permissions to update/delete Posts
- [x] **Task 4 -** Add Admin permissions to update/delete Users Profiles
- [x] **Task 5 -** Add Admin permissions to update/delete Comments
