### ISSUE TITLE
USER STORY: Contact Support Email Confirmation Received

### ISSUE THREAD

**Issue by b1ndark** [b1ndark/project4#27]
As a **User** I can **receive a confirmation from contact support** so that **I know that my message is being dealt with**

## Acceptance Criteria

- **Acceptance Criteria 1**
**Given** that I submit the form
**Then** I can receive an email confirming it

## Tasks

- [x] **Task 1 -** Setup the contact form
- [x] **Task 2 -** Setup emailJS
- [x] **Task 3 -** Create emailJS template
- [x] **Task 4 -** Create an auto reply email
