### ISSUE TITLE
USER STORY: 404 Error Page

### ISSUE THREAD

**Issue by b1ndark** [b1ndark/project4#28]
As a **User** I can **get 404 Error page** so that **I know that something went wrong**

##  Acceptance Criteria:

- **Acceptance Criteria 1**
**Given** that the page link is incorrect
**Then** I get a 404 Error page

- **Acceptance Criteria 2**
**Given** that the 404 Error page has a choice of going back to Home page

## Tasks

- [x] **Task 1 -** Setup a 404 Error page
- [x] **Task 2 -** A message explaining the problem
- [x] **Task 3 -** Shortcut to take the User back to home page
