### ISSUE TITLE
USER STORY: Log out

### ISSUE THREAD

**Issue by b1ndark** [b1ndark/project4#3]
As a **User** I can **click log out** so that **my account is logged off**

##  Acceptance Criteria:

- **Acceptance Criteria 1**
**Given** that I can access the logout in navbar
**Then** I click in logout link

- **Acceptance Criteria 2**
**Given** that I confirmed to logout
**Then** I am redirected to Home page

- **Acceptance Criteria 3**
**Given** that I been redirected
**Then** I get a logout confirmation message

## Tasks

- [x] **Task 1 -** Setup a Logout page
- [x] **Task 2 -** Add Logout link to navbar
- [x] **Task 3 -** Connect the navbar link to the page
- [x] **Task 4 -** Redirect to Home page after confirming 
- [x] **Task 5 -** Display a confirmation message
