### ISSUE TITLE
USER STORY: Post Search

### ISSUE THREAD

**Issue by b1ndark** [b1ndark/project4#30]
As a **User** I can **search** so that **I easily find the post**

## Acceptance Criteria

- **Acceptance Criteria 1**
**Given** that I want to search for a specific post
**Then** I can do it in the Forum

- **Acceptance Criteria 2**
**Given** that I have entered the post title
**Then** the post is presented

## Tasks

- [x] **Task 1 -** Setup a search bar in the navbar
- [x] **Task 2 -** Only display it when in the Forum
- [x] **Task 3 -** Add Error message to it
- [x] **Task 4 -** If post found to display it
