### ISSUE TITLE
USER STORY: Edit Post

### ISSUE THREAD

**Issue by b1ndark** [b1ndark/project4#31]
As a **User** I can **edit a post** so that **I can correct grammar errors**

## Acceptance Criteria

- **Acceptance Criteria 1**
**Given** that I have created the Post
**Then** I can access the Edit button

- **Acceptance Criteria 1**
**Given** that I have clicked the Edit button
**Then** I can Edit the post that I have created

## Tasks

- [x] **Task 1 -** Setup a edit post page
- [x] **Task 2 -** Link the edit button to it
- [x] **Task 3 -** Setup authentication so that only the post owner can see the Edit button
- [x] **Task 4 -** Once the User has clicked in it, takes to the edit post page
- [x] **Task 5 -** You then can either update/delete or go back
- [x] **Task 6 -** If post is edited you will get a confirmation page
