### ISSUE TITLE
USER STORY: Delete a Post

### ISSUE THREAD

**Issue by b1ndark** [b1ndark/project4#32]
As a **User** I can **delete a post that I have created** so that **the post is deleted from the forum**

## Acceptance Criteria

- **Acceptance Criteria 1**
**Given** that I have created the Post
**Then** I can access the Edit button

- **Acceptance Criteria 1**
**Given** that I have clicked the Edit button
**Then** I can Edit or Delete the post that I have created

- **Acceptance Criteria 3**
**Given** that I have clicked the Delete button
**Then** I get taken to Delete Post page where I can confirm it or not

## Tasks

- [x] **Task 1 -** Setup a Edit post page
- [x] **Task 2 -** Setup Delete post page
- [x] **Task 3 -** Link the edit button to it
- [x] **Task 4 -** Setup authentication so that only the post owner can see the Edit button
- [x] **Task 5 -** Once the User has clicked in it, takes to the edit post page
- [x] **Task 6 -** You then can either update/delete or go back
- [x] **Task 7 -** Once Delete button is pressed
- [x] **Task 8 -** You are taken to a page to confirm the deletion
- [x] **Task 9 -** If confirmed to Delete, You will get a confirmation message
