### ISSUE TITLE
USER STORY: Edit a Comment

### ISSUE THREAD

**Issue by b1ndark** [b1ndark/project4#33]
As a **user** I can **edit a comment** so that **comment is corrected/updated**

## Acceptance Criteria

- **Acceptance Criteria 1**
**Given** that I have created the Comment
**Then** I can access the Edit button

- **Acceptance Criteria 2**
**Given** that I have clicked the Edit button
**Then** I can Edit or Delete the comment that I have created

- **Acceptance Criteria 3**
**Given** that I have edited the comment
**Then** I get confirmation message

## Tasks

- [x] **Task 1 -** Setup a Edit comment page
- [x] **Task 2 -** Link the edit button to it
- [x] **Task 3 -** Setup authentication so that only the comment owner can see the Edit button
- [x] **Task 4 -** Once the User has clicked in it, takes to the edit comment page
- [x] **Task 5 -** You then can either update/delete or go back
- [x] **Task 6 -** If comment is edited, You will get a confirmation message
