### ISSUE TITLE
USER STORY: 500 Error Page

### ISSUE THREAD

**Issue by b1ndark** [b1ndark/project4#34]
As a **User** I can **get a 500 error page** so that **I know that there was a internal server error**

##  Acceptance Criteria:

- **Acceptance Criteria 1**
**Given** that there was an internal server error
**Then** I get a 500 Error page

- **Acceptance Criteria 2**
**Given** that the 500 Error page has a choice of going back to Home page

## Tasks

- [x] **Task 1 -** Setup a 500 Error page
- [x] **Task 2 -** A message explaining the problem
- [x] **Task 3 -** Shortcut to take the User back to home page
