### ISSUE TITLE
USER STORY: Profile

### ISSUE THREAD

**Issue by b1ndark** [b1ndark/project4#4]
As a **User** I can **access my profile** so that **I can update it**

## Acceptance Criteria

- **Acceptance Criteria 1**
**Given** that I want to access my profile
**Then** I can access it by clicking on my username link in the navbar

- **Acceptance Criteria 2**
**Given** that I have clicked it 
**Then** I am taken to the profile page

- **Acceptance Criteria 3**
**Given** that I been taken to the profile page
**Then** I can edit/update

## Tasks

- [x] **Task 1 -** Setup a profile page
- [x] **Task 2 -** Add Profile(username) link to the navbar
- [x] **Task 3 -** Link the Profile link to the page
- [x] **Task 4 -** Once clicked on Username, User is taken to profile page
- [x] **Task 5 -** Edit option is displayed if you are the owner of the profile
