### ISSUE TITLE
USER STORY: User Authentication

### ISSUE THREAD

**Issue by b1ndark** [b1ndark/project4#7]
As a **User** I can **authenticate** so that **I can edit personal info/posts/comments**

##  Acceptance Criteria:

- **Acceptance Criteria 1**
**Given** that I am the User of the profile
**When** I access the profile I can see the Edit button
**Then** I can Modify the personal info

- **Acceptance Criteria 2**
**Given** that I am the owner of the Post
**When** in the Post I can see the Edit button
**Then** I can Delete/update

- **Acceptance Criteria 3**
**Given** that I am the owner of the comment
**When** in the Post comments I can see the Edit button in my comments
**Then** I can Delete/Update

## Tasks

- [x] **Task 1 -** Setup the authentication
- [x] **Task 2 -** Checks for profile owner
- [x] **Task 3 -** Checks for post owner
- [x] **Task 4 -** Checks for comment owner
