### ISSUE TITLE
USER STORY: View Posts

### ISSUE THREAD

**Issue by b1ndark** [b1ndark/project4#8]
As a **User** I can **view a post** so that **I can be updated**

## Acceptance Criteria

- **Acceptance Criteria 1**
**Given** that a Post is created
**Then** I see the Users Posts

- **Acceptance Criteria 2**
**Given** that I have added Posts 
**Then** I can visualize my Posts and other Users

## Tasks

- [x] **Task 1 -** Create a View Post page
- [x] **Task 2 -** Add a link to the navbar so User can access it
- [x] **Task 3 -** Connect the navbar link to the page
- [x] **Task 4 -** Setup the Posts area so comments can be displayed
