### ISSUE TITLE
USER STORY: View Comments

### ISSUE THREAD

**Issue by b1ndark** [b1ndark/project4#9]
As a **User** I can **view comments** so that **I can see what people have commented on posts**

## Acceptance Criteria

- **Acceptance Criteria 1**
**Given** that a Post is created
**Then** I can comment

- **Acceptance Criteria 2**
**Given** that I have commented
**Then** I can visualize my comments and other Users

## Tasks

- [x] **Task 1 -** Create a View Post page
- [x] **Task 2 -** Add a link to the navbar so User can access it
- [x] **Task 3 -** Connect the navbar link to the page
- [x] **Task 4 -** Setup the comments area so comments can be displayed
- [x] **Task 5 -** Setup a comment box so Users can add comments
